### ISSUE TITLE
Build faild on simulator since the 1.17.0 version

### ISSUE THREAD

**Issue by aliabbas90** [Ubudu/IOS-SDK#1]
Hello, 

I can't build on simulator since the 1.17.0 version. I have the following error : 

Pods/UbuduSDK/UbuduSDK.framework/UbuduSDK, missing required architecture i386

No problem with the 1.16.5 version.

**Comment by zioolek** [comment]
Yes. We will include missing arch in next release. For now - please, build the app on a device...

**Comment by zioolek** [comment]
the simulator support is readded since 1.18.0
